USE MVP
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_insertemployeeskill')
BEGIN
	 DROP PROCEDURE dbo.usp_insertemployeeskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_updateemployeeskill')
BEGIN
	 DROP PROCEDURE dbo.usp_updateemployeeskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_deleteemployeeskill')
BEGIN
	 DROP PROCEDURE dbo.usp_deleteemployeeskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_getemployeeskill')
BEGIN
	 DROP PROCEDURE dbo.usp_getemployeeskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_insertjobskill')
BEGIN
	 DROP PROCEDURE dbo.usp_insertjobskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_updatejobskill')
BEGIN
	 DROP PROCEDURE dbo.usp_updatejobskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_deletejobskill')
BEGIN
	 DROP PROCEDURE dbo.usp_deletejobskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_getjobskill')
BEGIN
	 DROP PROCEDURE dbo.usp_getjobskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_insertjobs')
BEGIN
	 DROP PROCEDURE dbo.usp_insertjobs
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_updatejobs')
BEGIN
	 DROP PROCEDURE dbo.usp_updatejobs
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_deletejobs')
BEGIN
	 DROP PROCEDURE dbo.usp_deletejobs
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_getjobs')
BEGIN
	 DROP PROCEDURE dbo.usp_getjobs
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_insertemployee')
BEGIN
	 DROP PROCEDURE dbo.usp_insertemployee
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_updateemployee')
BEGIN
	 DROP PROCEDURE dbo.usp_updateemployee
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_deleteemployee')
BEGIN
	 DROP PROCEDURE dbo.usp_deleteemployee
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_getemployee')
BEGIN
	 DROP PROCEDURE dbo.usp_getemployee
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_insertskill')
BEGIN
	 DROP PROCEDURE dbo.usp_insertskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_updateskill')
BEGIN
	 DROP PROCEDURE dbo.usp_updateskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_deleteskill')
BEGIN
	 DROP PROCEDURE dbo.usp_deleteskill
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE  ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'usp_getskill')
BEGIN
	 DROP PROCEDURE dbo.usp_getskill
END
GO

IF EXISTS(SELECT * FROM sys.tables WHERE [Name] = 'JOBSKILLS')
BEGIN
	DROP TABLE JOBSKILLS
END

IF EXISTS(SELECT * FROM sys.tables WHERE [Name] = 'JOBS')
BEGIN
	DROP TABLE JOBS
END

IF EXISTS(SELECT * FROM sys.tables WHERE [Name] = 'EMPLOYEESKILLS')
BEGIN
	DROP TABLE EMPLOYEESKILLS
END

IF EXISTS(SELECT * FROM sys.tables WHERE [Name] = 'EMPLOYEE')
BEGIN
	DROP TABLE EMPLOYEE
END

IF EXISTS(SELECT * FROM sys.tables WHERE [Name] = 'SKILL')
BEGIN
	DROP TABLE SKILL
END

IF EXISTS(SELECT * FROM sys.types WHERE name = 'UDT_Skill' AND is_table_type = 1)
BEGIN
	DROP TYPE UDT_Skill
END
GO

--USE MASTER
--GO

--IF EXISTS(SELECT * FROM sys.databases WHERE [Name] = 'MVP')
--BEGIN
--	DROP DATABASE MVP
--END

--Declare @EmptyGuid UNIQUEIDENTIFIER
--Set @EmptyGuid = '00000000-0000-0000-0000-000000000000'

--INSERT INTO SKILL
--	(
--		Id,
--		Name,			
--		Description,	
--		CreatedBy,		
--		UpdatedBy		
--	)
--	VALUES
--	(
--		NEWID(),
--		'SQL',			
--		'SQL',	
--		@EmptyGuid,		
--		@EmptyGuid	
--	)

--	Declare @ErrorMessage	NVARCHAR(MAX) 
--	EXEC dbo.usp_getskill null, null, @ErrorMessage OUTPUT